import type { AppData, Project, Folder, User } from "./types";
import { uid } from "./utils";

export function defaultData(): AppData {
  const now = new Date();
  const iso = (daysAgo: number) => new Date(now.getTime() - daysAgo * 86400000).toISOString();

  const folders: Folder[] = [
    { id: "f_all", name: "جميع المشاريع" },
    { id: "f_edu", name: "محتوى تعليمي" },
    { id: "f_med", name: "محتوى طبي" },
    { id: "f_mkt", name: "التسويق" },
  ];

  const mockUser: User = {
    id: "user_demo",
    name: "مستخدم تجريبي",
    email: "demo@typo.ai",
    password: "123456",
    verified: true,
    avatarDataUrl: null,
    createdAt: iso(30),
  };

  const projects: Project[] = [
    {
      id: uid("proj"),
      title: "كيف يعمل الذكاء الاصطناعي؟",
      folderId: "f_edu",
      status: "completed",
      favorite: true,
      exportCount: 3,
      createdAt: iso(12),
      updatedAt: iso(2),
      settings: {
        contentType: "تعليمي",
        audience: "صناع المحتوى",
        level: "مبتدئ",
        tone: "مبسطة",
        language: "العربية الفصحى",
        size: "1080x1350",
        slideCount: 6,
        cta: "تابع الحساب",
        templateId: "tahrir",
        paletteId: "p1",
        font: "tajawal",
        brandKit: {
          enabled: true,
          showLogo: false,
          showAccountName: true,
          showSlideNumber: true,
          placement: "bottom-left",
        },
      },
      slides: [
        { id: uid("s"), type: "cover", title: "كيف يعمل الذكاء الاصطناعي؟", body: "دليل مبسّط لفهم أساسيات الذكاء الاصطناعي" },
        { id: uid("s"), type: "content", title: "ما هو الذكاء الاصطناعي؟", body: "الذكاء الاصطناعي هو قدرة الآلة على محاكاة الذكاء البشري في التعلم والاستنتاج واتخاذ القرار." },
        { id: uid("s"), type: "content", title: "البيانات هي الأساس", body: "يعتمد الذكاء الاصطناعي على كميات ضخمة من البيانات لتدريب النماذج وتحسين النتائج." },
        { id: uid("s"), type: "content", title: "التعلم الآلي", body: "هو فرع من الذكاء الاصطناعي يتعلم فيه النموذج الأنماط من البيانات دون برمجة صريحة." },
        { id: uid("s"), type: "content", title: "التطبيقات اليومية", body: "من المساعدات الصوتية إلى التوصيات الذكية، الذكاء الاصطناعي حولنا في كل مكان." },
        { id: uid("s"), type: "ending", title: "تابعنا للمزيد", body: "شاركنا اهتمامك بالتقنية وابقَ على اطلاع", ctaText: "تابع الحساب" },
      ],
      caption: "الذكاء الاصطناعي ليس سحرًا، بل علم قائم على البيانات والتعلم الآلي. تعرّف على أساسياته في هذا الكاروسيل 🤖\n\n#الذكاء_الاصطناعي #التقنية",
      hashtags: ["#الذكاء_الاصطناعي", "#التقنية", "#تعلم", "#محتوى_تعليمي"],
    },
    {
      id: uid("proj"),
      title: "5 نصائح للنوم الصحي",
      folderId: "f_med",
      status: "draft",
      favorite: false,
      exportCount: 0,
      createdAt: iso(8),
      updatedAt: iso(5),
      settings: {
        contentType: "نصائح",
        audience: "الجمهور العام",
        level: "مبتدئ",
        tone: "ودية",
        language: "العربية الفصحى",
        size: "1080x1080",
        slideCount: 6,
        cta: "احفظ المنشور",
        templateId: "wadeh",
        paletteId: "p4",
        font: "cairo",
        brandKit: {
          enabled: false,
          showLogo: false,
          showAccountName: false,
          showSlideNumber: false,
          placement: "bottom-right",
        },
      },
      slides: [
        { id: uid("s"), type: "cover", title: "5 نصائح للنوم الصحي", body: "خطوات بسيطة لنوم أفضل وراحة أكبر" },
        { id: uid("s"), type: "content", title: "ثابت على موعد", body: "حاول النوم والاستيقاظ في نفس الوقت يوميًا لتنظيم ساعتك البيولوجية." },
        { id: uid("s"), type: "content", title: "ابتعد عن الشاشات", body: "الضوء الأزرق يثبط الميلاتونين، أوقف الشاشات قبل النوم بساعة." },
        { id: uid("s"), type: "content", title: "بيئة مريحة", body: "غرفة مظلمة وهادئة وباردة تساعد على نوم عميق." },
        { id: uid("s"), type: "content", title: "تجنب الكافيين", body: "ابتعد عن القهوة والشاي بعد الظهر لتجنب الأرق." },
        { id: uid("s"), type: "ending", title: "احفظ هذه النصائح", body: "طبّقها الليلة ولاحظ الفرق", ctaText: "احفظ المنشور" },
      ],
      caption: "نومك يؤثر على كل شيء في يومك! جرّب هذه النصائح 😴\n\n#الصحة #النوم #نصائح_صحية",
      hashtags: ["#الصحة", "#النوم", "#نصائح_صحية", "#صحة"],
    },
    {
      id: uid("proj"),
      title: "مقارنة: التسويق الرقمي vs التقليدي",
      folderId: "f_mkt",
      status: "completed",
      favorite: true,
      exportCount: 1,
      createdAt: iso(20),
      updatedAt: iso(10),
      settings: {
        contentType: "مقارنة",
        audience: "أصحاب المشاريع",
        level: "متوسط",
        tone: "احترافية",
        language: "العربية الفصحى",
        size: "1080x1350",
        slideCount: 5,
        cta: "شارك المنشور",
        templateId: "tabayun",
        paletteId: "p2",
        font: "ibm",
        brandKit: {
          enabled: true,
          showLogo: true,
          showAccountName: true,
          showSlideNumber: true,
          placement: "top-left",
        },
      },
      slides: [
        { id: uid("s"), type: "cover", title: "التسويق الرقمي vs التقليدي", body: "أيهما يناسب مشروعك؟" },
        { id: uid("s"), type: "content", title: "الوصول", body: "الرقمي يصل لجمهور عالمي بسرعة، والتقليدي محدود جغرافيًا." },
        { id: uid("s"), type: "content", title: "التكلفة", body: "الرقمي أكثر مرونة في الميزانية وقابل للقياس بدقة." },
        { id: uid("s"), type: "content", title: "التفاعل", body: "الرقمي يتيح تفاعلًا فوريًا، والتقليدي أحادي الاتجاه." },
        { id: uid("s"), type: "ending", title: "شارك رأيك", body: "أي نوع تفضّل لمشروعك؟", ctaText: "شارك المنشور" },
      ],
      caption: "كل نوع تسويق له مكانه. الأهم أن تعرف جمهورك وأهدافك 📊\n\n#التسويق #ريادة_الأعمال",
      hashtags: ["#التسويق", "#ريادة_الأعمال", "#التسويق_الرقمي"],
    },
    {
      id: uid("proj"),
      title: "خطوات بدء مشروعك الأول",
      folderId: "f_mkt",
      status: "draft",
      favorite: false,
      exportCount: 0,
      createdAt: iso(3),
      updatedAt: iso(1),
      settings: {
        contentType: "خطوات",
        audience: "رواد الأعمال",
        level: "مبتدئ",
        tone: "تحفيزية",
        language: "اللهجة المصرية",
        size: "1080x1920",
        slideCount: 7,
        cta: "تابع الحساب",
        templateId: "hadith",
        paletteId: "p1",
        font: "tajawal",
        brandKit: {
          enabled: false,
          showLogo: false,
          showAccountName: false,
          showSlideNumber: false,
          placement: "bottom-left",
        },
      },
      slides: [
        { id: uid("s"), type: "cover", title: "خطوات بدء مشروعك الأول", body: "من الفكرة للتنفيذ في 5 خطوات" },
        { id: uid("s"), type: "content", title: "اعرف فكرتك", body: "حدد المشكلة اللي بتحلها والقيمة اللي بتقدمها." },
        { id: uid("s"), type: "content", title: "ادرس السوق", body: "افهم جمهورك ومنافسيك قبل ما تبدأ." },
        { id: uid("s"), type: "content", title: "خطط لميزانيتك", body: "اعرف تكاليفك المتوقعة ومصادر التمويل." },
        { id: uid("s"), type: "content", title: "ابني هويتك", body: "الاسم والشعار والصوت بتاع علامتك التجارية." },
        { id: uid("s"), type: "content", title: "ابدأ وجرّب", body: "أطلق نسخة بسيطة وطورها بناءً على ردود الفعل." },
        { id: uid("s"), type: "ending", title: "لو عجبك المحتوى", body: "تابعنا للمزيد من نصائح ريادة الأعمال", ctaText: "تابع الحساب" },
      ],
      caption: "أهم خطوة هي إنك تبدأ! 💪\n\n#ريادة_الأعمال #مشاريع",
      hashtags: ["#ريادة_الأعمال", "#مشاريع", "#نصائح"],
    },
  ];

  return {
    users: [mockUser],
    currentUserId: null,
    projects,
    folders,
    brandKit: {
      instagramHandle: "@typo.ai",
      logoDataUrl: null,
      primaryColor: "#6D5EFC",
      font: "tajawal",
    },
    exportRecords: [
      { id: uid("exp"), projectId: projects[0].id, projectTitle: projects[0].title, slideCount: 6, size: "1080x1350", exportedAt: iso(2) },
      { id: uid("exp"), projectId: projects[2].id, projectTitle: projects[2].title, slideCount: 5, size: "1080x1350", exportedAt: iso(10) },
      { id: uid("exp"), projectId: projects[0].id, projectTitle: projects[0].title, slideCount: 6, size: "1080x1350", exportedAt: iso(1) },
    ],
    favoriteTemplates: ["tahrir", "tabayun"],
  };
}
